### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/collect_stata#29]
Congratulations @mpahl. Please bump the version of your libary.
VERSION = "0.0.1" is too modest, now, that it does something.

**Comment by hansendx** [comment]
I only saw your comment after i already set the tag of the lattest master commit to v0.0.1

I would argue, that the code, that came in through #11 is the first version here.
Since I am not sure how much is going to change i would keep the version at 0.0.1 and increase it only in the minor, patch parts till we are sure, that the project can be used in production.
Otherwise, problems like #27 would already increment the major version.

In the [SemVer specs](https://semver.org/) 0.y.z versions can be used at the stage this project is currently still at.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by afuetterer** [comment]
Okay, then.
So this can be closed, I guess?

Relates to #33.
